comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    path('post-comment/<int:lock_id>/', views.Post_comment, name='post_comment'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include  # add this
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),  # Django admin route
    path('auth/', include("authentication.urls")),  # Auth routes - login / register
    path('', include("lock.urls")),  # UI Kits Html files
    # path('api/', include('Api.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler400 = 'lock.views.HandleErrors.bad_request'
handler403 = 'lock.views.HandleErrors.permission_denied'
handler404 = 'lock.views.HandleErrors.page_not_found'
handler500 = 'lock.views.HandleErrors.server_error'

lock/urls.py
# -*- encoding: utf-8 -*-
'''
Copyright (c) 2019 - present AppSeed.us
'''

from django.urls import path
from lock.views.HomeView import HomeView, ChartView, global_search
from lock.views.LockView import LockListView, LockCreateView, LockDetailView, LockUpdateView, LockDeleteView
from lock.views.LocationView import LocationListView, LocationCreateView, LocationDeleteView
from lock.views.ManufacturerView import ManufacturerListView, ManufacturerCreateView, ManufacturerDeleteView, ManufacturerUpdateView
from lock.views.ActivityView import ActivityListView, ActivityDeleteView
from lock.views.BorrowRecordView import BorrowRecordListView, BorrowRecordCreateView, BorrowRecordDetailView, BorrowRecordDeleteView, BorrowRecordClose, auto_lock
from lock.views.ProfileView import ProfileCreateView, ProfileUpdateView, ProfileDetailView
from lock.views.DataCenterView import DataCenterView, download_data
from lock.views.EmployeesView import EmployeeView, EmployeeCreateView, EmployeeUpdate, EmployeeDetailView, EmployeeDeleteView
from lock.views.NoticeView import NoticeListView, NoticeUpdateView

urlpatterns = [
    # 主页url
    path('', HomeView.as_view(), name='home'),
    # 行李锁url
    path('lock/list', LockListView.as_view(), name='lock_list'),
    path('lock/create', LockCreateView.as_view(), name='lock_create'),
    path('lock/update/<int:pk>/', LockUpdateView.as_view(), name='lock_update'),
    path('lock/delete/<int:pk>/', LockDeleteView.as_view(), name='lock_delete'),
    path('lock/detail/<int:pk>/', LockDetailView.as_view(), name='lock_detail'),

    # 位置url
    path('location/list', LocationListView.as_view(), name='location_list'),
    path('location/create', LocationCreateView.as_view(), name='location_create'),
    path('location/delete/<int:pk>/', LocationDeleteView.as_view(), name='location_delete'),

    # 制造商url
    path('manufacturer/list', ManufacturerListView.as_view(), name='manufacturer_list'),
    path('manufacturer/create', ManufacturerCreateView.as_view(), name='manufacturer_create'),
    path('manufacturer/delete/<int:pk>/', ManufacturerDeleteView.as_view(), name='manufacturer_delete'),
    path('manufacturer/update/<int:pk>/', ManufacturerUpdateView.as_view(), name='manufacturer_update'),

    # 用户日志url
    path('user/activity/list', ActivityListView.as_view(), name='user_activity_list'),
    path('user/activity/list/<int:pk>/', ActivityDeleteView.as_view(), name='user_activity_delete'),

    # 用户资料url
    path('user/profile-create/', ProfileCreateView.as_view(), name='profile_create'),
    path('user/<int:pk>/profile/', ProfileDetailView.as_view(), name='profile_detail'),
    path('user/<int:pk>/profile-update/', ProfileUpdateView.as_view(), name='profile_update'),

    # 使用记录url
    path('record-create/', BorrowRecordCreateView.as_view(), name='record_create'),
    path('record-create/autocomplete-lock-name/', auto_lock, name='auto_lock_name'),
    path('record-list/', BorrowRecordListView.as_view(), name='record_list'),
    path('record-detail/<int:pk>/', BorrowRecordDetailView.as_view(), name='record_detail'),
    path('record-delete/<int:pk>/', BorrowRecordDeleteView.as_view(), name='record_delete'),
    path('record-close/<int:pk>/', BorrowRecordClose.as_view(), name='record_close'),

    # 数据中心url
    path('data-center/', DataCenterView.as_view(), name='data_center'),
    path('data-download/<str:model_name>/', download_data, name='data_download'),

    # 图表url
    path('charts/', ChartView.as_view(), name='chart'),

    # 全局搜索url
    path('global-search/', global_search, name='global_search'),

    # 员工url
    path('employees/', EmployeeView.as_view(), name='employees_list'),
    path('employess-create/', EmployeeCreateView.as_view(), name='employees_create'),
    path('employees-detail/<int:pk>', EmployeeDetailView.as_view(), name='employees_detail'),
    path('employees-update/<int:pk>', EmployeeUpdate, name='employee_update'),
    path('employess-delete/<int:pk>', EmployeeDeleteView.as_view(), name='employees_delete'),

    # 通知url
    path('notice-list/', NoticeListView.as_view(), name='notice_list'),
    path('notice-update/', NoticeUpdateView.as_view(), name='notice_update'),
]

lock/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from datetime import timedelta
from PIL import Image
from django.conf import settings

# Create your models here.

# 定义锁状态choices
LOCK_STATUS = [
    (0, '被使用'),
    (1, '未使用'),
]

# 定义活动类型choices
OPERATION_TYPE = [
    ('success', '创建'),
    ('warning', '更新'),
    ('danger', '删除'),
    ('info', '关闭')
]

# 定义性别choices
GENDER = [
    ('m', '男'),
    ('f', '女')
]

# 定义借用记录状态
BORROW_RECORD_STATUS = [
    (0, '使用中'),
    (1, '已归还')
]


# 位置模型
class Location(models.Model):
    name = models.CharField(max_length=50, blank=True)  # 位置名
    created_at = models.DateTimeField(default=timezone.now)  # 创建时间

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_list')

    class Meta:
        db_table = 'location'  # 定义表名


# 制造商模型
class Manufacturer(models.Model):
    name = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=50, blank=True)
    contact = models.EmailField(max_length=50, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_by = models.CharField(max_length=20, default='Admin')
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('manufacturer_list')

    class Meta:
        db_table = 'manufacturer'


# 电子锁模型
class Lock(models.Model):
    title = models.CharField('Title', max_length=20)
    description = models.TextField()
    created_at = models.DateTimeField('Created Time', default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    total_borrow_times = models.PositiveIntegerField(default=0)
    quantity = models.PositiveIntegerField(default=10)
    location = models.ForeignKey(  # 定义多对一外键
        Location,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,  # 联级表删除时外键置空
        related_name='location'
    )

    manufacturer = models.ForeignKey(
        Manufacturer,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='manufacturer'
    )

    status = models.IntegerField(choices=LOCK_STATUS, default=1)
    delete_status = models.IntegerField(default=0)  # 删除状态： 0.正常/1.删除
    lockshelf_number = models.CharField('Lockshelf Number', max_length=10, default='0001')
    updated_by = models.CharField(max_length=20, default='Admin')

    def get_absolute_url(self):
        return reverse('lock_list')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'lock'


# 用户日志模型
class UserActivity(models.Model):
    created_by = models.CharField(max_length=20, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    operation_type = models.CharField(choices=OPERATION_TYPE, default='success', max_length=20)  # 选择活动类型
    target_model = models.CharField(max_length=20, default='')  # 操作的目标模型
    detail = models.CharField(max_length=50, default='')
    delete_status = models.IntegerField(default=0)  # 删除状态： 0.正常/1.删除

    def get_absolute_url(self):
        return reverse('user_activity_list')

    class Meta:
        db_table = 'user_activity'


# 用户资料模型
class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)  # 一对一关系，级联User模型
    bio = models.TextField()  # 简介
    profile_pic = models.ImageField(upload_to='profile/%Y%m%d/', blank=True, null=True, default=settings.AVATAR_DEFAULT)    # 用户头像图片
    age = models.PositiveIntegerField(default=18)
    gender = models.CharField(max_length=10, choices=GENDER, default='m')
    phone_number = models.CharField(max_length=30, blank=True)
    email = models.EmailField(max_length=50, blank=True)

    def save(self, *args, **kwargs):
        # 调用原有的sava()功能
        profile = super(Profile, self).save(*args, **kwargs)

        # 按固定宽度缩放图片大小
        if self.profile_pic and not kwargs.get('update_fields'):
            image = Image.open(self.profile_pic)
            (x, y) = image.size  # 获取图片宽高（宽，高）
            new_x = 400
            new_y = int(new_x * (y / x))
            resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)  # 裁剪图片
            resized_image.save(self.profile_pic.path)

        return profile

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('home')

    class Meta:
        db_table = 'profile'


# 使用记录
class BorrowRecord(models.Model):
    borrower = models.CharField(max_length=20, blank=False)
    lock = models.CharField(max_length=20, blank=False)
    borrower_phone_number = models.CharField(max_length=30, blank=True)
    location = models.CharField(max_length=50, blank=False)
    manufacturer = models.CharField(max_length=50, blank=False)
    quantity = models.PositiveIntegerField(default=1)

    start_day = models.DateTimeField(default=timezone.now)
    end_day = models.DateTimeField(default=timezone.now() + timedelta(hours=1))

    open_or_close = models.IntegerField(choices=BORROW_RECORD_STATUS, default=0)
    delete_status = models.IntegerField(default=0)  # 删除状态： 0.正常/1.删除

    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.CharField(max_length=20, blank=True)
    closed_at = models.DateTimeField(auto_now=True)
    closed_by = models.CharField(max_length=20, default='')

    def get_absolute_url(self):
        return reverse('record_list')

    def __str__(self):
        return self.borrower + '->' + self.lock

    class Meta:
        db_table = 'borrow_record'

lock/views/ActivityView.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import ListView, View
from django.db.models import Q
from lock.models import UserActivity
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import messages

# 分页每页显示条数
PAGINATOR_NUMBER = 5

# 跳转页数
delpage = 0


# 用户日志
class ActivityListView(LoginRequiredMixin, ListView):
    model = UserActivity
    context_object_name = 'activities'
    template_name = 'user_activity_list.html'
    count_total = 0
    search_value = ''
    created_by = ''
    order_field = '-created_at'
    all_users = User.objects.values()
    user_list = [x['username'] for x in all_users]

    def get_queryset(self):
        global delpage
        delpage = self.request.GET.get('page')

        search = self.request.GET.get('search')
        filter_user = self.request.GET.get('created_by')

        all_activities = UserActivity.objects.filter(delete_status=0)

        if filter_user:
            self.created_by = filter_user
            all_activities = all_activities.filter(Q(created_by=self.created_by) and Q(delete_status=0))

        if search:
            all_activities = all_activities.filter(Q(target_model__icontains=search) and Q(delete_status=0))
            self.search_value = search

        self.count_total = all_activities.count()
        paginator = Paginator(all_activities, PAGINATOR_NUMBER)
        page = self.request.GET.get('page')
        response = paginator.get_page(page)
        return response

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ActivityListView, self).get_context_data(**kwargs)
        context['count_total'] = self.count_total
        context['search'] = self.search_value
        context['user_list'] = self.user_list
        context['created_by'] = self.created_by
        context['orderby'] = self.order_field
        context['objects'] = self.get_queryset()
        return context


class ActivityDeleteView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        log_pk = kwargs["pk"]
        delete_log = UserActivity.objects.get(pk=log_pk)
        messages.error(request, f"已删除用户日志，ID: << {delete_log.id} >> ")
        delete_log.delete_status = 1
        delete_log.save()

        return HttpResponseRedirect(reverse_lazy('user_activity_list') + '?page=' + str(delpage))

lock/views/DataCenterView.py
import pandas as pd
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView
from lock.groups_permissions import allowed_groups
from django.apps import apps
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from util.useful import get_n_days_ago
from lock.groups_permissions import check_user_group

# 文件日期
TODAY = get_n_days_ago(0, "%Y%m%d")
# 模型列表
allowed_models = ['Lock', 'Location', 'Manufacturer', 'Profile', 'UserActivity', 'BorrowRecord']


# 数据中心视图
@method_decorator(allowed_groups(group_name=['download_data']), name='dispatch')
class DataCenterView(LoginRequiredMixin, TemplateView):
    template_name = 'download_data.html'

    def get(self, request, *args, **kwargs):
        data = {m.objects.model._meta.db_table:
                    {"source": pd.DataFrame(list(m.objects.all().values())),
                     "path": f"{str(settings.BASE_DIR)}/datacenter/{m.__name__}_{TODAY}.csv",
                     "file_name": f"{m.__name__}_{TODAY}.csv"} for m in apps.get_models() if
                m.__name__ in allowed_models}
        count_total = {k: v['source'].shape[0] for k, v in data.items()}
        return render(request, self.template_name, context={'model_list': count_total})


# 数据下载
@login_required(login_url='login')
@allowed_groups(group_name=['download_data'])
def download_data(request, model_name):
    check_user_group(request.user, "download_data")  # 判断超级管理员是否在所在组

    download = {m.objects.model._meta.db_table:
                    {"source": pd.DataFrame(list(m.objects.all().values())),
                     "path": f"{str(settings.BASE_DIR)}/datacenter/{m.__name__}_{TODAY}.csv",
                     "file_name": f"{m.__name__}_{TODAY}.csv"} for m in apps.get_models() if
                m.__name__ in allowed_models}

    download[model_name]['source'].to_csv(download[model_name]['path'], index=False, encoding='utf_8_sig')
    # download_file = pd.read_csv(download[model_name]['path'], encoding='utf-8')
    # response = HttpResponse(download_file, content_type="text/csv")
    response = HttpResponse(open(download[model_name]['path'], 'r', encoding='utf-8'), content_type="text/csv")
    response['Content-Disposition'] = f"attachment;filename={download[model_name]['file_name']}"
    return response

lock/views/HandleErrors.py
from django.shortcuts import render


# 网站错误处理
# 404 找不到页面资源
def page_not_found(request, exception):
    context = {}
    response = render(request, "errors/404.html", context=context)
    response.status_code = 404
    return response


# 500 服务器后台内部错误
def server_error(request, exception=None):
    context = {}
    response = render(request, "errors/500.html", context=context)
    response.status_code = 500
    return response


# 403 拒绝执行客户端请求
def permission_denied(request, exception=None):
    context = {}
    response = render(request, "errors/403.html", context=context)
    response.status_code = 403
    return response


# 400 客户端请求的语法错误
def bad_request(request, exception=None):
    context = {}
    response = render(request, "errors/400.html", context=context)
    response.status_code = 400
    return response

lock/views/NoticeView.py
from django.views.generic import ListView, View
from lock.groups_permissions import SuperUserRequiredMixin
from django.shortcuts import redirect


# 通知列表
class NoticeListView(SuperUserRequiredMixin, ListView):
    context_object_name = 'notices'
    template_name = 'notice_list.html'

    # 未读通知的查询集
    def get_queryset(self):
        return self.request.user.notifications.unread()


# 通知更新状态
class NoticeUpdateView(SuperUserRequiredMixin, View):
    """Update Status of Notification"""

    # 处理 get 请求
    def get(self, request):
        # 获取未读消息
        notice_id = request.GET.get('notice_id')
        # 更新单条通知
        if notice_id:
            request.user.notifications.get(id=notice_id).mark_as_read()
            return redirect('notice_list')
        # 更新全部通知
        else:
            request.user.notifications.mark_all_as_read()
            return redirect('notice_list')

templates/lock/lock_detail.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}
{% block title %} 查看行李锁{% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="pcoded-content">
        <div class="pcoded-inner-content">
            <div class="page-header">
                <div class="page-block">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="page-header-title">
                                <h5 class="m-b-10">行李锁管理</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <!-- [ breadcrumb ] end -->
            <div class="main-body">
                <div class="page-wrapper">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="card">
                                <div class="card-header">
                                    <h5><i class="fas fa-book"></i> 详细信息 : << {{ lock.title }} >> </h5>
                                </div>

                                <div class="card-block">
                                    <div class="col-md-12">
                                        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                                            <li class="nav-item">
                                                <a class="nav-link active" id="pills-home-tab" data-toggle="pill"
                                                   href="#pills-basic" role="tab" aria-controls="pills-basic"
                                                   aria-selected="true">概括</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link" id="pills-profile-tab" data-toggle="pill"
                                                   href="#pills-profile" role="tab" aria-controls="pills-profile"
                                                   aria-selected="false">描述</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link" id="pills-contact-tab" data-toggle="pill"
                                                   href="#pills-contact" role="tab" aria-controls="pills-contact"
                                                   aria-selected="false">锁架位置</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link" id="pills-record-tab" data-toggle="pill"
                                                   href="#pills-record" role="tab" aria-controls="pills-record"
                                                   aria-selected="false">使用记录</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link" id="pills-comment-tab" data-toggle="pill"
                                                   href="#pills-comment" role="tab" aria-controls="pills-comments"
                                                   aria-selected="false">评论</a>
                                            </li>
                                        </ul>
                                        <div class="tab-content" id="pills-tabContent">
                                            <!-- 概括 -->
                                            <div class="tab-pane fade show active" id="pills-basic" role="tabpanel"
                                                 aria-labelledby="pills-home-tab">
                                                <div class='row'>
                                                    <div class='col-6'>
                                                        <p>名称: {{ lock.title }} </p>
                                                        <p>位置: {{ lock.location }} </p>
                                                        <p>制造商: {{ lock.manufacturer }} </p>
                                                        <p>数量: {{ lock.quantity }} </p>
                                                    </div>
                                                    <div class='col-6'>
                                                        <p>创建于: {{ lock.created_at|date:"Y/m/d H:i" }} </p>
                                                        <p>最后更新者: <span
                                                                class="badge badge-info">{{ lock.updated_by }}</span>
                                                            at {{ lock.updated_at|date:"Y/m/d H:i" }} </p>
                                                        <p>使用次数: {{ lock.total_borrow_times }} </p>
                                                        <p>当前状态 : {{ lock.get_status_display }} </p>
                                                    </div>
                                                </div>
                                            </div>
                                            <!-- 描述 -->
                                            <div class="tab-pane fade" id="pills-profile" role="tabpanel"
                                                 aria-labelledby="pills-profile-tab">
                                                <p class="mb-0">
                                                    {{ lock.description }}
                                                </p>
                                            </div>
                                            <!-- 锁架位置 -->
                                            <div class="tab-pane fade" id="pills-contact" role="tabpanel"
                                                 aria-labelledby="pills-contact-tab">
                                                <div class='row'>
                                                    <div class='col-6'>
                                                        <p> 位置 Id: {{ lock.location }}{{ lock.lockshelf_number }}</p>
                                                        <p> 车厢: {{ lock.location }} </p>
                                                        <p> 锁架: {{ lock.lockshelf_number }} </p>
                                                    </div>
                                                </div>
                                            </div>
                                            <!-- 使用记录 -->
                                            <div class="tab-pane fade" id="pills-record" role="tabpanel"
                                                 aria-labelledby="pills-record-tab">
                                                {% if related_records %}
                                                    <table class="table table-sm">
                                                    <thead>
                                                    <tr>
                                                        <th scope="col">使用者</th>
                                                        <th scope="col">行李锁名称</th>
                                                        <th scope="col">制造商</th>
                                                        <th scope="col">开始时间 - 结束时间</th>
                                                        <th scope="col">状态</th>
                                                        <th scope="col">归还时间</th>
                                                    </tr>
                                                    </thead>
                                                    <tbody>

                                                    {% for record in related_records %}
                                                        <tr>
                                                            <td>{{ record.borrower }} </td>
                                                            <td>{{ record.lock }}</td>
                                                            <td>{{ record.manufacturer }}</td>
                                                            <td>{{ record.start_day | date:"Y/m/d H:i" }}
                                                                - {{ record.end_day | date:"Y/m/d H:i" }}</td>
                                                            <td>{{ record.get_open_or_close_display }}</td>
                                                            <td>{{ record.closed_at | date:"Y/m/d H:i" }}</td>
                                                        </tr>
                                                    {% endfor %}
                                                {% endif %}
                                                </tbody>
                                                </table>

                                            </div>

                                            <!-- Comments -->
                                            <div class="tab-pane fade" id="pills-comment" role="tabpanel"
                                                 aria-labelledby="pills-comment-tab">
                                                {% if user.is_authenticated %}
                                                    <div>
                                                        <form
                                                                action="{% url 'comment:post_comment' lock.id %}"
                                                                method="POST"
                                                        >
                                                            {% csrf_token %}
                                                            <div class="form-group">
                                                                <label for="body">
                                                                    <strong>
                                                                        添加评论：
                                                                    </strong>
                                                                </label>

                                                                <div>
                                                                    {{ comment_form.media }}
                                                                    {{ comment_form.body }}
                                                                </div>
                                                            </div>

                                                            <!-- 提交按钮 -->
                                                            <button type="submit" class="btn btn-success ">发送</button>
                                                        </form>
                                                    </div>
                                                    <br>
                                                {% else %}
                                                    <br>
                                                    <h5 class="row justify-content-center">
                                                        请先<a href="{% url 'login' %}">登录</a>再进行评论！
                                                    </h5>
                                                    <br>
                                                {% endif %}
                                                <h4>全部 {{ comments.count }} 条评论</h4>
                                                <div>
                                                    {% for comment in comments %}
                                                        <hr>
                                                        <p>
                                                            <strong style="color: rgb(175, 31, 55)">
                                                                {{ comment.user }}
                                                            </strong>
                                                            发表于
                                                            <span style="color: green">
                                             {{ comment.created_at|date:"Y/m/d H:i" }}
                                        </span> :
                                                        </p>
                                                        <p>{{ comment.body|safe }}</p>

                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <a href="{% url 'lock_list' %}" class='btn btn-dark'>返回列表</a>
                            <a href="{% url 'lock_update' lock.id %}" class='btn btn-primary'>更新</a>

                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
    <script>
        $(".django-ckeditor-widget").removeAttr('style');
    </script>

{% endblock javascripts %}