core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include  # add this
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),  # Django admin route
    path('auth/', include("authentication.urls")),  # Auth routes - login / register
    path('', include("lock.urls")),  # UI Kits Html files
    # path('api/', include('Api.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler400 = 'lock.views.HandleErrors.bad_request'
handler403 = 'lock.views.HandleErrors.permission_denied'
handler404 = 'lock.views.HandleErrors.page_not_found'
handler500 = 'lock.views.HandleErrors.server_error'

lock/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from datetime import timedelta
from PIL import Image
from django.conf import settings

# Create your models here.

# 定义锁状态choices
LOCK_STATUS = [
    (0, '被使用'),
    (1, '未使用'),
]

# 定义活动类型choices
OPERATION_TYPE = [
    ('success', '创建'),
    ('warning', '更新'),
    ('danger', '删除'),
    ('info', '关闭')
]

# 定义性别choices
GENDER = [
    ('m', '男'),
    ('f', '女')
]

# 定义借用记录状态
BORROW_RECORD_STATUS = [
    (0, '使用中'),
    (1, '已归还')
]


# 位置模型
class Location(models.Model):
    name = models.CharField(max_length=50, blank=True)  # 位置名
    created_at = models.DateTimeField(default=timezone.now)  # 创建时间

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_list')

    class Meta:
        db_table = 'location'  # 定义表名


# 制造商模型
class Manufacturer(models.Model):
    name = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=50, blank=True)
    contact = models.EmailField(max_length=50, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_by = models.CharField(max_length=20, default='Admin')
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('manufacturer_list')

    class Meta:
        db_table = 'manufacturer'


# 电子锁模型
class Lock(models.Model):
    title = models.CharField('Title', max_length=20)
    description = models.TextField()
    created_at = models.DateTimeField('Created Time', default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    total_borrow_times = models.PositiveIntegerField(default=0)
    quantity = models.PositiveIntegerField(default=10)
    location = models.ForeignKey(  # 定义多对一外键
        Location,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,  # 联级表删除时外键置空
        related_name='location'
    )

    manufacturer = models.ForeignKey(
        Manufacturer,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='manufacturer'
    )

    status = models.IntegerField(choices=LOCK_STATUS, default=1)
    delete_status = models.IntegerField(default=0)  # 删除状态： 0.正常/1.删除
    lockshelf_number = models.CharField('Lockshelf Number', max_length=10, default='0001')
    updated_by = models.CharField(max_length=20, default='Admin')

    def get_absolute_url(self):
        return reverse('lock_list')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'lock'


# 用户日志模型
class UserActivity(models.Model):
    created_by = models.CharField(max_length=20, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    operation_type = models.CharField(choices=OPERATION_TYPE, default='success', max_length=20)  # 选择活动类型
    target_model = models.CharField(max_length=20, default='')  # 操作的目标模型
    detail = models.CharField(max_length=50, default='')
    delete_status = models.IntegerField(default=0)  # 删除状态： 0.正常/1.删除

    def get_absolute_url(self):
        return reverse('user_activity_list')

    class Meta:
        db_table = 'user_activity'


# 用户资料模型
class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)  # 一对一关系，级联User模型
    bio = models.TextField()  # 简介
    profile_pic = models.ImageField(upload_to='profile/%Y%m%d/', blank=True, null=True, default=settings.AVATAR_DEFAULT)    # 用户头像图片
    age = models.PositiveIntegerField(default=18)
    gender = models.CharField(max_length=10, choices=GENDER, default='m')
    phone_number = models.CharField(max_length=30, blank=True)
    email = models.EmailField(max_length=50, blank=True)

    def save(self, *args, **kwargs):
        # 调用原有的sava()功能
        profile = super(Profile, self).save(*args, **kwargs)

        # 按固定宽度缩放图片大小
        if self.profile_pic and not kwargs.get('update_fields'):
            image = Image.open(self.profile_pic)
            (x, y) = image.size  # 获取图片宽高（宽，高）
            new_x = 400
            new_y = int(new_x * (y / x))
            resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)  # 裁剪图片
            resized_image.save(self.profile_pic.path)

        return profile

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('home')

    class Meta:
        db_table = 'profile'


# 使用记录
class BorrowRecord(models.Model):
    borrower = models.CharField(max_length=20, blank=False)
    lock = models.CharField(max_length=20, blank=False)
    borrower_phone_number = models.CharField(max_length=30, blank=True)
    location = models.CharField(max_length=50, blank=False)
    manufacturer = models.CharField(max_length=50, blank=False)
    quantity = models.PositiveIntegerField(default=1)

    start_day = models.DateTimeField(default=timezone.now)
    end_day = models.DateTimeField(default=timezone.now() + timedelta(hours=1))

    open_or_close = models.IntegerField(choices=BORROW_RECORD_STATUS, default=0)
    delete_status = models.IntegerField(default=0)  # 删除状态： 0.正常/1.删除

    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.CharField(max_length=20, blank=True)
    closed_at = models.DateTimeField(auto_now=True)
    closed_by = models.CharField(max_length=20, default='')

    def get_absolute_url(self):
        return reverse('record_list')

    def __str__(self):
        return self.borrower + '->' + self.lock

    class Meta:
        db_table = 'borrow_record'

templates/charts.html
{% extends "layouts/base.html" %}
{% load static %}
{% block title %} 图表 {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}

    <link rel="stylesheet" href="{% static '/assets/plugins/chart-morris/css/morris.css' %}">

{% endblock stylesheets %}

{% block content %}

    <div class="pcoded-content">
        <div class="pcoded-inner-content">
            <!-- [ breadcrumb ] start -->
            <div class="page-header">
                <div class="page-block">
                    <div class="row align-items-center">
                        <!-- <div class="col-md-12">
                            <div class="page-header-title">
                                <h5 class="m-b-10">Morris Chart</h5>
                            </div>

                        </div> -->
                    </div>
                </div>
            </div>
            <div class="main-body">
                <div class="page-wrapper">
                    <!-- [ Main Content ] start -->
                    <div class="row">
                        <!-- [ Morris Chart ] start -->
                        <div class="col-xl-6">
                            <div class="card">
                                <div class="card-header">
                                    <h5>行李锁库存</h5>
                                </div>
                                <div class="card-block">
                                    <figure class="highcharts-figure">
                                        <div id="lock-count" style="height:400px"></div>
                                    </figure>
                                </div>
                            </div>
                        </div>

                        <div class="col-xl-6">
                            <div class="card">
                                <div class="card-header">
                                    <h5>使用最多的行李锁</h5>
                                </div>
                                <div class="card-block">
                                    <figure class="highcharts-figure">
                                        <div id="top-borrow" style="height:400px"></div>
                                    </figure>

                                </div>
                            </div>
                        </div>

                        <div class="col-xl-6">
                            <div class="card">
                                <div class="card-header">
                                    <h5>使用记录状态</h5>
                                </div>
                                <div class="card-block">
                                    <figure class="highcharts-figure">
                                        <div id="record-status" style="height:400px"></div>
                                    </figure>

                                </div>
                            </div>
                        </div>


                        <div class="col-xl-6">
                            <div class="card">
                                <div class="card-header">
                                    <h5>近7天使用记录</h5>
                                </div>
                                <div class="card-block">
                                    <figure class="highcharts-figure">
                                        <div id="weekly-borrow" style="height:400px"></div>
                                    </figure>

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
    <script type="text/javascript" src="https://cdn.highcharts.com.cn/highcharts/highcharts.js"></script>
    <script type="text/javascript" src="https://cdn.highcharts.com.cn/highcharts/modules/exporting.js"></script>
    <script type="text/javascript" src="https://cdn.highcharts.com.cn/highcharts/modules/export-data.js"></script>
    <script type="text/javascript" src="https://cdn.highcharts.com.cn/highcharts/modules/accessibility.js"></script>
    <script type="text/javascript" src="https://cdn.highcharts.com.cn/highcharts/modules/cylinder.js"></script>
    <script type="text/javascript" src="https://cdn.highcharts.com.cn/highcharts-3d.js"></script>
    <script type="text/javascript" src="https://img.hcharts.cn/highcharts-plugins/highcharts-zh_CN.js"></script>
    <script type="text/javascript">
        const chart_top_stock_lock = new Highcharts.Chart({
            chart: {
                renderTo: 'lock-count',
                type: 'column',
                options3d: {
                    enabled: true,
                    alpha: 5,
                    beta: 15,
                    depth: 50,
                }
            },
            title: {
                text: '库存Top5'
            },
            xAxis: {
                categories: {{top_5_lock_titles|safe}}
            },
            yAxis: {title: {text: '库存'}},
            series: [{
                type: 'column',
                name: '数量',
                data: {{top_5_lock_quantities}},
            }]
        });

        new Highcharts.Chart({
            chart: {
                renderTo: 'top-borrow',
                type: 'column',
            },
            title: {
                text: '最多使用'
            },
            xAxis: {
                categories: {{top_borrow_titles|safe}},

            },
            yAxis: {title: {text: '次数'}},
            series: [{
                type: 'column',
                name: '次数',
                data: {{top_borrow_times}},
                color: "#47CC8A",
            }]
        });


        new Highcharts.Chart({
            chart: {
                type: 'pie',
                renderTo: 'record-status',
            },

            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },

            title: {
                text: '正使用 / 已归还'
            },
            accessibility: {
                point: {
                    valueSuffix: '%'
                }
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        format: '<b>{point.name}</b>: {point.y:.0f}'
                    }
                }
            },
            series: [{
                name: '记录',
                colorByPoint: true,
                data: [{
                    name: '正使用',
                    y: {{r_open |safe}},
                    color: "#8085E9",
                },

                    {
                        name: '已归还',
                        y: {{r_close |safe}},
                        color: "#F7A35C",
                    }
                ]
            }]
        });


        new Highcharts.Chart('weekly-borrow', {

            title: {
                text: '使用记录 / 周'
            },

            subtitle: {
                text: '按周计算'
            },

            yAxis: {
                title: {
                    text: '总使用数'
                }
            },

            xAxis: {
                categories: {{week_borrow|safe}}
            },

            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle'
            },

            plotOptions: {
                series: {
                    label: {
                        connectorAllowed: false
                    },
                }
            },

            series: [{
                name: '使用数',
                data: {{count_week_borrow|safe}}
            }],

            responsive: {
                rules: [{
                    condition: {
                        maxWidth: 500
                    },
                    chartOptions: {
                        legend: {
                            layout: 'horizontal',
                            align: 'center',
                            verticalAlign: 'bottom'
                        }
                    }
                }]
            }

        });

    </script>

{% endblock javascripts %}

templates/global_search.html
{% extends "layouts/base.html" %}
{% load lock_extras %}
{% block title %} 搜索结果 {% endblock %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="pcoded-content">
        <div class="pcoded-inner-content">
            <div class="page-header">
                <div class="page-block">
                    <!-- Title -->
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="page-header-title">
                                <h5 class="m-b-10">搜索结果</h5>

                            </div>

                        </div>
                    </div>
                </div>

            </div>

            <br>
            <div class="main-body">
                <div class="page-wrapper">
                    <div class="row">
                        {% if locations %}
                            <div class="col-xl-6">
                                <div class="card">
                                    <div class="card-header">
                                        <h5>位置</h5>
                                    </div>

                                    <div class="card-block ">
                                        <div class="table-responsive table-hover">
                                            <table class="table">
                                                <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>名称</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                {% for location in locations %}
                                                    <tr>
                                                        <th scope="row">{{ location.id }}</th>
                                                        <td>{{ location.name }}</td>
                                                    </tr>
                                                {% endfor %}

                                                </tbody>
                                            </table>
                                        </div>

                                    </div>
                                </div>

                            </div>
                        {% endif %}

                        {% if manufacturers %}
                            <div class="col-xl-6">
                                <div class="card">
                                    <div class="card-header">
                                        <h5>制造商</h5>
                                    </div>

                                    <div class="card-block ">
                                        <div class="table-responsive table-hover">
                                            <table class="table">
                                                <thead>
                                                <tr>
                                                    <th>名称</th>
                                                    <th>城市</th>
                                                    <th>联系方式</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                {% for manufacturer in manufacturers %}
                                                    <tr>
                                                        <td>{{ manufacturer.name }}</td>
                                                        <td>{{ manufacturer.city }}</td>
                                                        <td>{{ manufacturer.contact }}</td>
                                                    </tr>
                                                {% endfor %}

                                                </tbody>
                                            </table>
                                        </div>

                                    </div>
                                </div>

                            </div>
                        {% endif %}

                        {% if locks %}
                            <div class="col-xl-12">
                                <div class="card">
                                    <div class="card-header">
                                        <h5>行李锁</h5>
                                    </div>

                                    <div class="card-block ">
                                        <div class="table-responsive table-hover">
                                            <table class="table">
                                                <thead>
                                                <tr>
                                                    <th>名称</th>
                                                    <th>状态</th>
                                                    <th>数量</th>
                                                    <th>制造商</th>
                                                    <th>位置</th>
                                                    <th>锁架号</th>

                                                </tr>
                                                </thead>
                                                <tbody>
                                                {% for lock in locks %}
                                                    <tr>
                                                        <td><a href="{% url 'lock_detail' lock.id %}"
                                                               class="badge badge-secondary">{{ lock.title }}</a></td>
                                                        <td>{{ lock.get_status_display }}</td>
                                                        <td>{{ lock.quantity }}</td>
                                                        <td>{{ lock.manufacturer }}</td>
                                                        <td>{{ lock.location }}</td>
                                                        <td>{{ lock.lockshelf_number }}</td>
                                                    </tr>
                                                {% endfor %}

                                                </tbody>
                                            </table>
                                        </div>

                                    </div>
                                </div>

                            </div>
                        {% endif %}

                        {% if records %}
                            <div class="col-xl-12">
                                <div class="card">
                                    <div class="card-header">
                                        <h5>使用记录</h5>
                                    </div>

                                    <div class="card-block ">
                                        <div class="table-responsive table-hover">
                                            <table class="table">
                                                <thead>
                                                <tr>
                                                    <th>名称</th>
                                                    <th>行李锁</th>
                                                    <th>数量</th>
                                                    <th>使用时间</th>
                                                    <th>归还时间</th>
                                                    <th>状态</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                {% for record in records %}
                                                    <tr>
                                                        <td><a href="{% url 'record_detail' record.pk %}"
                                                               class="badge badge-secondary">{{ record.borrower }}</a>
                                                        </td>
                                                        <td>{{ record.lock|truncatewords:3 }}</td>
                                                        <td>{{ record.quantity }}</td>
                                                        <td>{{ record.start_day|date:"H-i-s" }}</td>
                                                        <td>{{ record.end_day|date:"H-i-s" }}</td>
                                                        <td>{{ record.get_open_or_close_display }}</td>
                                                    </tr>
                                                {% endfor %}

                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/user_activity_list.html
{% extends "layouts/base.html" %}
{% load lock_extras %}
{% block title %} 用户日志 {% endblock %}
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="pcoded-content">
        <div class="pcoded-inner-content">
            <div class="page-header">
                <div class="page-block">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="page-header-title">
                                <h5 class="m-b-10">用户日志</h5>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <br>
            <div class="main-body">
                <div class="page-wrapper">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="card">
                                <div class="card-header">
                                    <h5>总共 {{ count_total }} 条日志</h5>
                                </div>
                                {% show_messages %}
                                <div class="card-block ">
                                    <div class='row'>

                                        <!-- Dropdown list -->
                                        <div class="col-6">
                                            <div class="btn-group ">
                                                {% if created_by == '' %}
                                                    <button class="btn btn-light dropdown-toggle" type="button"
                                                            data-toggle="dropdown" aria-haspopup="true"
                                                            aria-expanded="true">选择用户
                                                    </button>
                                                {% else %}
                                                    <button class="btn btn-secondary dropdown-toggle" type="button"
                                                            data-toggle="dropdown" aria-haspopup="true"
                                                            aria-expanded="false">{{ created_by }} </button>
                                                {% endif %}

                                                <div class="dropdown-menu">
                                                    {% for user in user_list %}
                                                        <a class="dropdown-item"
                                                           href="{% url 'user_activity_list' %}?created_by={{ user }}&search={{ search }}">{{ user }}</a>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </div>
                                        <!-- Search box -->
                                        <div class="col-6">
                                            <form class="form-inline mb-2">
                                                <div class="form-group  mb-2">
                                                    <input type="text" class="form-control" name="search" id='search'
                                                           placeholder="搜索目标对象" value="">
                                                </div>
                                                <button type="submit"
                                                        class="btn btn-secondary ml-2 mb-2 btn-sm">搜索
                                                </button>
                                            </form>
                                        </div>
                                    </div>

                                    <div class="table-responsive table-hover">
                                        <table class="table">
                                            <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>名称</th>
                                                <th>动作</th>
                                                <th>目标对象</th>
                                                <th>时间</th>
                                                <th>内容</th>
                                                <th>操作</th>
                                            </tr>
                                            </thead>
                                            <tbody>

                                            {% for activity in activities %}
                                                <tr>
                                                    <th scope="row">{{ activity.id }}</th>
                                                    <td>{{ activity.created_by }}</td>
                                                    <td class="table-{{ activity.operation_type }}">
                                                        {{ activity.get_operation_type_display }} </td>
                                                    <td>{{ activity.target_model }}</td>
                                                    <td>{{ activity.created_at|date:"Y-m-d H:i" }} </td>
                                                    <td>{{ activity.detail }} </td>
                                                    <td><a href="{% url 'user_activity_delete' activity.pk %}"
                                                           class="badge badge-danger"><i
                                                            class="feather icon-trash-2"></i> 删除</a></td>
                                                </tr>

                                            {% endfor %}


                                            </tbody>
                                        </table>
                                    </div>
                                <div class="row">
                                        <div class="col-4">
                                        </div>
                                        <div class='col-8'>
                                            {% show_pagination %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block javascripts %}{% endblock javascripts %}